config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.completed = params['task']['completed'].to_i == 1
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.delete
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details %>
  </div>
  <div class="form-group">
  <%= f.label :completed %>
  <%= f.check_box :completed, as: :boolean %>
  </div>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
    <% if task.completed %>
    <input name=name id=id type=checkbox checked>
    <% else %>
    <input name=name id=id type=checkbox>
    <% end %>
    <%= link_to task.title, task_path(task) %>
    <%= link_to "delete", task_path(task), method: :delete%>
  </li>
  <% end %>
</ul>

<hr>
<%= link_to "+ Add new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <%= f.submit class:'btn btn-primary'%>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "edit task", edit_task_path(@task) %>
<p><%= @task.details %></p>
<% if @task.completed %>
    <input name=name id=id type=checkbox checked><p>This task is completed</p>
<% else %>
    <input name=name id=id type=checkbox><p>This task is not completed </p>
<% end %>
<%= link_to "back to list", tasks_path %>